### PR TITLE
Added a Retro Theme (no icons yet)

### PR DESCRIPTION
**Pull request by 0b101**
SC1SC2SC3

### CODE REVIEW

**Comment by quentinguidee** [comment]
Oh thank you @0b101 ! This theme looks really cool! :)
Do you plan to make the icons before we merge this ?

**Comment by 0b101** [comment]
@quentinguidee Yes and thank you. It shouldn’t take too long.

**Comment by quentinguidee** [comment]
Okay perfect! :)

Also, for the toolbox, I see that there is a problem with the left and right borders. I suggest you to invert "HeaderBackground" and "HeaderText"/"HeaderBorder". This way, I think this will render correctly (but the look will be a little bit different). I let you decide !

**Comment by lelahx** [comment]
I also noticed a little problem: the cursor is the same color as the elemnts in the "Atom" app, hence, highlighting of the selected element is invisible. There's also no more syntax highlighting of the python code, and the color of the line numbers sidebar doesn't match the rest of the theme.

**Comment by 0b101** [comment]
Yeah, I saw that too. I’ll fix it when I do the icons.

**Comment by quentinguidee** [comment]
Hello! First of all, thank you for this theme!

In Omega 1.20, we introduced "3rd party themes". Here's how it works:

---

To make your own theme, you can use our 3rd party theme system :
* Create a new repository with your theme (there is an example [here](https://github.com/Omega-Numworks/Omega-Theme-Example)). Note: You can put several themes in the same repository.
* It's done!

To install your new theme, use these flags during the compilation:

```
make THEME_REPO={your repository url} THEME_NAME={Your theme name}
```

Example:
```
make THEME_REPO=https://github.com/Omega-Numworks/Omega-Theme-Example.git THEME_NAME=omega_blue
```

---

If you have any questions about this, feel free to ask!

**Pull request closed without merging**
